import React from 'react';
import DashboardSidebar from './DashboardSidebar/DashboardSidebar';

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
  }
  



const DashboardLayout = ({children}) => {
    return (
        <div>
            <DashboardSidebar/>
            {children}
        </div>
    );
};

export default DashboardLayout;